name: ecommerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 3.3.1
  cloud_firestore: ^5.2.0
  cupertino_icons: 1.0.6
  firebase_auth: ^5.1.3
  firebase_analytics: ^11.1.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.1.0
  flutter_bloc: 8.1.3
  flutter_carousel_widget: 2.1.0
  flutter_dash: 1.0.0
  flutter_facebook_auth: 5.0.11
  flutter_native_splash: 2.3.9
  google_sign_in: 5.4.4
  lorem_ipsum: 0.0.3
  persistent_bottom_nav_bar_v2: 5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/Syfer.jpg
    - assets/images/mastercard.png

flutter_native_splash:
  color: "#673AB7"
  image: assets/images/splash.png

  android_12:
    color: "#673AB7"
    image: assets/images/splash.png
